# Generated by Django 3.2.21 on 2023-10-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('room_name', models.CharField(max_length=100)),
                ('room_floor', models.IntegerField(default=0)),
            ],
        ),
    ]
